AutoCarChile/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('apps.core.urls')),
    path('client/', include('apps.clients.urls')),
    path('users/', include('apps.user.urls')),
    path('accidents/', include('apps.accidents.urls')),
    path('reparacion/', include('apps.reparacion.urls')),
    path('', include('apps.sucursal.urls')),

    #path('accounts/', include('django.contrib.auth.urls')),
]

apps/accidents/urls.py
from .views import (AssignCraneAccident, AssignWorkShopAccident, ListAccidentView, ListPendingAccidentView, NewAccident,DetailAccident,AssignAccident,ListAllAccidentView,AssignWorkshopCraneAccident, ReportesAccidentView)
from django.urls import path

app_name = 'accidents'

urlpatterns = [
    path('new-accident/<int:pk>',NewAccident.as_view(),name='add_accident'),
    path('accident/<int:pk>',DetailAccident.as_view(),name='view_accident'),
    path('accident/list_pending', ListPendingAccidentView.as_view(), name="pending_list"),
    path('accident/list', ListAccidentView.as_view(), name="list_accidents"),
    path('accident/list/report', ReportesAccidentView.as_view(), name="report_accidents"),
    path('accident/assing/<int:pk>', AssignAccident.as_view(), name="assing"),
    path('accident/assing/workshop/<int:pk>', AssignWorkshopCraneAccident.as_view(), name="assing_workshop"),
    # path('accident/assing/crane/<int:pk>', AssignCraneAccident.as_view(), name="assing_crane"),
    path('accident/list/all', ListAllAccidentView.as_view(), name="list"),
]

apps/clients/urls.py
from django.urls import path
from .views import denuncia, poliza, siniestro, vehiculo, finalizar,valid_policy

urlpatterns = [
    #path('', index, name="index"),
    #path('contact/', contact, name="contact"),
    #path('registro/', registro, name="registro"),
    path('denuncia/', denuncia, name="denuncia"),
    path('poliza/', poliza, name="poliza"),
    path('siniestro/', siniestro, name="siniestro"),
    path('vehiculo/', vehiculo, name="vehiculo"),
    path('finalizar/', finalizar, name="finalizar"),   
    path('valid_policy/', valid_policy, name="valid_policy"),    
]

apps/clients/models.py
from django.forms import model_to_dict
from django.db import models
import uuid

from django.db.models.fields.related import ForeignKey

# Create your models here.

class Cliente(models.Model):
    rut = models.CharField(max_length=14,unique=True)
    nombre = models.CharField(max_length=50)
    apellido = models.CharField(max_length=50)
    fecha_nacimiento = models.DateField(default=None,null=False)
    nro_doc = models.CharField(max_length=14)
    email = models.EmailField()
    telefono = models.CharField(max_length=14)
    direccion = models.CharField(max_length=50)
    # deuda_total = models.DecimalField(max_digits=10,decimal_places=2,default=0)
    
    def __str__(self):
        return self.rut

    def nombreCompleto(self):
        return self.nombre + " " + self.apellido

    class Meta:
        db_table = 'Cliente'
        default_permissions = ()
        permissions = (
            ("view_cliente",     "Ver cliente"),
            ("add_cliente",      "Registrar cliente"),
            ("change_cliente",   "Actualizar cliente"),
            ("delete_cliente",   "Eliminar cliente"),
        )


    




#------------------------------------------------------------------------------------------

class Consulta_poliza(models.Model):
    rut = models.CharField(max_length=14)
    poliza = models.CharField(max_length=10)

    def __str__(self):
        return self.rut

    class Meta:
        db_table = 'consulta_poliza'
        default_permissions = ()
        permissions = (
            ("view_consultarPoliza",     "Consultar poliza con RUT"),
        )
        
#--------------------------------------------------------------------------------------------

opciones_marcas = [
    [0, "Chevrolet"],
    [1, "Hyundai"],
    [2, "Toyota"],
    [3, "Peugeot"],
    [4, "Nissan"],
    [5, "Kia"],
    [6, "Mazda"],
    [7, "Koenigsegg"],
    [8, "Mitsubishi"],
    [9, "Chrysler"],
    [10, "Ford"],
    [11, "Chevrolet"],
    [12, "Dodge"],
]

class Vehiculo(models.Model):
    patente = models.CharField(max_length=10)
    marca = models.IntegerField(choices=opciones_marcas)
    modelo = models.CharField(max_length=50)
    year = models.CharField(max_length=4,verbose_name="año",default=None,null=True)
    nuevo = models.BooleanField(null=True)
    cliente = models.ForeignKey(Cliente,related_name="dueno_auto",on_delete=models.CASCADE)
    tipo = models.CharField(max_length=50,default=None,null=True)


    def __str__(self):
        return self.patente

    class Meta:
        db_table = 'vehiculo'
        default_permissions = ()
        permissions = (
            ("view_vehiculo",     "Ver vehiculo"),
            ("add_vehiculo",      "Registrar vehiculo"),
            ("change_vehiculo",   "Actualizar vehiculo"),
            ("delete_vehiculo",   "Eliminar vehiculo"),
        )


class Poliza(models.Model):
    numero_poliza = models.IntegerField(default=None,null=False,unique=True)
    cantidad_maxima = models.DecimalField(max_digits=10,decimal_places=2,default=1000)
    detalles = models.TextField(default=None)
    cliente = models.ForeignKey(Cliente,related_name="dueno_poliza",on_delete=models.CASCADE)
    vehiculo = models.ForeignKey(Vehiculo,related_name="vehiculo_asociado",on_delete=models.CASCADE)

    def __str__(self) -> str:
        return str(self.numero_poliza)
    
    def to_json(self):
        data = model_to_dict(self,exclude=('cliente','vehiculo',))
        data["cliente"] = model_to_dict(self.cliente)
        data["vehiculo"] = model_to_dict(self.vehiculo)
        return data

    class Meta:
        db_table = 'poliza'
        default_permissions = ()
        permissions = (
            ("view_poliza",     "Ver poliza"),
            ("add_poliza",      "Registrar poliza"),
            ("change_poliza",   "Actualizar poliza"),
            ("delete_poliza",   "Eliminar poliza"),
        )

apps/clients/forms.py
from django import forms
from .models import Cliente, Consulta_poliza, Vehiculo
from django.contrib.auth.forms import UserCreationForm
from django.forms import ValidationError



class ContactoForm(forms.ModelForm):

    def clean_rut(self):
        rut = self.cleaned_data["rut"]
        existe = Cliente.objects.filter(rut__iexact=rut).exists()

        if existe:
            raise ValidationError("El rut ingresado ya existe!")

        return rut

    class Meta:
        model = Cliente
        fields = '__all__'

class CustomUserCreationForm(UserCreationForm):
    pass
 

class PolizaForm(forms.ModelForm):

    def clean_poliza(self):
        poliza = self.cleaned_data["poliza"]
        existe = Consulta_poliza.objects.filter(poliza__iexact=poliza).exists()

        if existe:
            return poliza
        else:
            raise ValidationError("Póliza vigente!")

        return poliza

    class Meta:
        model = Consulta_poliza
        fields = '__all__'
    
    
# class form_contactoForm(forms.ModelForm): 

#     class Meta:
#         model = form_contacto
#         fields = '__all__'

class VehiculoForm(forms.ModelForm): 
    def clean_patente(self):
        patente = self.cleaned_data["patente"]
        existe = Vehiculo.objects.filter(patente__iexact=patente).exists()

        if existe:
            raise ValidationError("La patente ingresada ya existe!")

        return patente

    class Meta:
        model = Vehiculo
        fields = '__all__'

    

apps/clients/views.py
from django.contrib.auth.decorators import login_required
from .forms import ContactoForm, CustomUserCreationForm, PolizaForm, VehiculoForm
from apps.core.decorators import group_required,superuser_required,permission_required
from .models import Cliente, Consulta_poliza, Vehiculo,Poliza
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_http_methods
from django.views.decorators.csrf import csrf_exempt
from django.utils.decorators import method_decorator
from django.contrib.auth import authenticate, login
from django.http import JsonResponse, response
from apps.accidents.models import Accident
from django.contrib import messages


# Create your views here.

# def index(request):
#     return render(request, 'app/index.html')

def denuncia(request):
    return render(request, 'app/denuncia.html')

def finalizar(request):
    return render(request, 'app/finalizar.html')

def vehiculo(request):
    data = {
        'form': VehiculoForm()
    }

    if request.method == 'POST':
        formulario = VehiculoForm(data=request.POST)
        if formulario.is_valid():
            formulario.save()
            data["mensaje"] = "Datos Guardados Correctamente"
            return redirect(to='finalizar')

        else:
            data["form"] = formulario


    return render(request, 'app/vehiculo.html', data)

# @permission_required('clients.view_poliza')
@require_http_methods(["GET"])
def poliza(request):
    return render(request, 'app/poliza.html', {
        'tituloPagina' : 'Buscar polizas',
        'tituloSeccion' : 'Buscar polizas',
    })

def siniestro(request):
    data = {
        'form': ContactoForm()
    }

    if request.method == 'POST':
        formulario = ContactoForm(data=request.POST)
        if formulario.is_valid():
            formulario.save()
            data["mensaje"] = "Mensaje Enviado"
            return redirect(to='vehiculo')

        else:
            data["form"] = formulario

    return render(request, 'app/siniestro.html', data)

# decorador para aceptar solo GET
# @permission_required('clients.view_poliza')
@require_http_methods(["GET"])
def valid_policy(request):
    # se inicializa la respuesta
    response = {}
    # Poliza
    # numero_poliza
    rut = request.GET.get("rut",None)
    # verificar que exista tanto cliente como codigo de poliza
    # si alguno de los dos es nullo(None) entonces la condicion no se cumple
    if rut:
        policies = Poliza.objects.filter(cliente__rut=rut)
        results = []
        for policy in policies:
            datos = policy.to_json()
            datos['vehiculo']['nuevo'] = "SI" if datos['vehiculo']['nuevo'] == True else "NO"
            last_accident = Accident.objects.exclude(estado=6).filter(poliza=policy).last()
            if last_accident:
                datos['siniestro']=last_accident.to_json()
            results.append(datos)
        response = results
    return JsonResponse(response,safe=False)

apps/clients/templates/app/contact.html
{% extends 'base/base.html' %}{% load static %}

{% block contenido %}
	<div class="banner1">
		<div class="container">
		</div>
	</div>

	<div class="services-breadcrumb">
		<div class="container">
			<ul>
				<li><a href="{% url 'index' %}">Inicio</a><i>|</i></li>
				<li>Contacto</li>
			</ul>
		</div>
	</div>

	<div class="mail">
		<div class="container">
			<h3 class="title_denuncia">Contáctanos</h3>
			<p class="quia">Completa todos los campos</p>

			<div class="w3ls_map">
				<iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d26627.887720352774!2d-70.7207941313252!3d-33.46269641928642!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x9662c48fa8d3a271%3A0x21fdf5e9699638c3!2sSantiago%2C%20Estaci%C3%B3n%20Central%2C%20Regi%C3%B3n%20Metropolitana!5e0!3m2!1ses!2scl!4v1617513142751!5m2!1ses!2scl" width="0" height="0" frameborder="0" style="border:0" allowfullscreen></iframe>
			</div>
			<div class="col-md-4 wthree_contact_left">
				<h4>Contact Center</h4>
				<p>Ruta G60 KM 6 Isla Chocalán
					<span>Melipilla,Chile</span></p>
				<ul>
					<li><span class="glyphicon glyphicon-earphone" aria-hidden="true"></span>+569 85060623</li>
					<li><span class="glyphicon glyphicon-envelope" aria-hidden="true"></span><a href="mailto:l.ignaciomatus@gmail.com">l.ignaciomatus@gmail.com</a></li>
					<li><span class="glyphicon glyphicon-user" aria-hidden="true"></span><a>Lunes a viernes 9:00 a 18:00 hrs.</a></li>
				</ul>
			</div>
			{% load crispy_forms_tags %}
			<div class="col-md-8 wthree_contact_left ">
				<h4>Formulario de Contacto</h4>
				<form action="" method="POST">
					{% csrf_token %}
					{{ form | crispy }}
					<input type="submit" name="Enviar">
					<input type="reset" name="Limpiar Campos">
					{{mensaje}}
					
				</form>
			</div>
			<div class="clearfix"> </div>
		</div>
	</div>


{% endblock contenido %}

apps/clients/templates/app/denuncia.html
{% extends 'base/baseOut.html'%} {% load static %}

{% block contenido %}
	<div class="services-breadcrumb">
		<div class="container">
            
			<ul>
				<li><a href="{% url 'index' %}">Inicio</a><i>|</i></li>
				<li>Denuncia Siniestro Auto</li>
			</ul>
		</div>
	</div>

	<div class="services">
    <div class="container">
        <h3 class="denuncia">Lo que debes saber acerca de tu Siniestro Auto</h3>
        <p class="quia">Automóviles</p>
		<br>
		<div class="">
			<div class="">
				<span class="glyphicon glyphicon-thumbs-up" aria-hidden="true"></span>
				<h4 class="titulo_denuncia">¿Qué hacer en caso de un siniestro de vehículo?</h4>
				<h4 class="text_denuncia">Si en el siniestro resultaran personas lesionadas, debes dar cuenta de inmediato a la unidad policial más próxima, mediante parte policial. En el caso que tengas imposibilidad física debidamente acreditada, y no puedas acudir a la unidad policial, debes dar cuenta del siniestro a la compañía tan pronto sea posible.</h4>
			</div>
		</div>
		<br>
		<br>
		<div class="">
			<div class="">
				<span class="glyphicon glyphicon-thumbs-up" aria-hidden="true"></span>
				<h4 class="titulo_denuncia">¿Qué documentos debo tener en caso de siniestro?</h4>
				<h4 class="text_denuncia">Los documentos necesarios que debe presentar el asegurado al momento del denuncio del siniestro son:</h4>
				<br>
				<ol>
					<li><strong>Licencia de Conducir</strong></li>
					<li><strong>Permiso de Circulación</strong></li>
					<li><strong>Revisión técnica al día</strong></li>
					
				  </ol>
			</div>
		</div>
		<br>
		<div class="">
			<div class="">
				<span class="glyphicon glyphicon-thumbs-up" aria-hidden="true"></span>
				<h4 class="titulo_denuncia">Sobre la liquidación de tu siniestro</h4>
				<h4 class="text_denuncia">Al recibir el denuncio del siniestro, autoCar te asignará un liquidador y un taller.</h4>
				<br>
				<ol>
					<li><strong> Coordinación con Taller:</strong> Te recomendamos coordinar con el taller una fecha y hora de entrega de tu vehículo para evitar colas o espera.</li>
					<br>
					<li><strong>Liquidación del Siniestro:</strong> El liquidador revisará los antecedentes del siniestro y determinará si la cobertura aplica. En caso de ser un siniestro cubierto por la Compañía, el liquidador dará la orden de reparación al Taller.</li>
					<br>
					<li><strong>Entrega de tu vehículo: </strong>El taller se comunicará contigo para coordinar una fecha y hora de entrega de tu vehículo reparado.</li>
					
				  </ol>
			</div>
		</div>
		<br>
		<div class="">
			<div class="">
				<span class="glyphicon glyphicon-exclamation-sign" aria-hidden="true"></span>
				<h4 class="titulo_denuncia">Revisa el estado de tu siniestro</h4>
				<h4 class="text_denuncia">Nuestro servicio "Seguimiento en línea del estado de tu Siniestro", te  permitirá hacer un seguimiento en tiempo real de los siniestros vehiculares que declares. Debes ingresar al portal de clientes con tu usuario y clave; luego en la sección siniestros ver "Estado de Siniestros".</h4>
			</div>
		</div>
            <div class="clearfix"> </div>
        </div>
    </div>
</div>


{% endblock contenido %}

apps/clients/templates/app/finalizar.html
{% extends 'base/base.html' %}
{% load static %}

{% block contenido %}
<div class="services-breadcrumb">
		<div class="container">
            
			<ul>
				<li><a href="{% url 'index' %}">Inicio</a><i>|</i></li>
				<li>Proceso Terminado</li>
			</ul>
		</div>
	</div>

	<br>
	<br>
	<br>
	<br>
	<h3 class="title_denuncia">Felicitaciones!</h3>
	<br>

    <p class="quia">Has completado la solicitud con todos los datos del siniestro.</p>
	

	<div class="contacto_siniestro">
		<div class="formulario">      
			<h1 class="ache1">Dirígite al menú principal</h1>
			<h3 class="ache2">Haz click en Volver.</h3>
			<a href="{% url 'index' %}" class="button_finalizar">Volver</a>          
			{{mensaje}}
    	</div>  
  </div>

{% endblock contenido %}

apps/clients/templates/app/index.html
{% extends 'base/base.html' %}
{% load static %}

{% block contenido %}
	<div class="banner">
		<div class="container">
			<div class="w3ls_banner_info">
				<h2>Bienvenidos</h2>
				<p>Prestamos excelentes servicios en caso que tengas problemas con tu vehículo, no pierdas más tiempo, Contáctanos llamando al 600 200 100</p>
				<div class="wthree_more">
					<a href="{% url 'contact' %}" class="button--wayra button--border-thick button--text-upper button--size-s">Más Información</a>
				</div>
			</div>
		</div>
	</div>
	<div class="banner-bottom">
		<div class="container">
			<div class="col-md-6 banner_bottom_left">
				<h3>Servicios que puedes acceder con solo comunicarnos</h3>
				<p><i>Házlo ahora! No pierdas más tiempo.</i> En proceso</p>
				<div class="wthree_more wthree_more1">
					<a href="{% url 'index' %}" class="button--wayra button--border-thick button--text-upper button--size-s">Leer Más</a>
				</div>
			</div>
			<div class="col-md-6 banner_bottom_right">
				<div class="wthree_banner_bottom_right_grids">
					<div class="col-md-6 banner_bottom_right_grid">
						<div class="view view-tenth">
							<div class="agile_text_box">
								<i></i>
								<h3>Taller Mecánico</h3>
								<p>Contamos con profesionales trabajando en un buen taller, consiguiendo que tu vehículo luzca tal y como estaba antes.</p>
							</div>
							
						</div>
					</div>
					<div class="col-md-6 banner_bottom_right_grid">
						<div class="view view-tenth">
							<div class="agile_text_box">
								<i class="clock"></i>
								<h3>Servicio De Asistencia Con Grúa</h3>
								<p>Permite la facilidad de poder retirar tu automóvil siniestrado o con desperfecto hacia los talleres mecánicos.</p>
							</div>
							
						</div>
					</div>
					<div class="clearfix"> </div>
				</div>
				<div class="wthree_banner_bottom_right_grids">
					<div class="col-md-6 banner_bottom_right_grid">
						<div class="view view-tenth">
							<div class="agile_text_box">
								<i class="shipping"></i>
								<h3>Servicio De Reparación</h3>
								<p>Te ayudamos a que los daños materiales del vehículo sean reparados, y su proceso de reparación o restitución material sea más eficiente.</p>
							</div>
							
						</div>
					</div>
					<div class="col-md-6 banner_bottom_right_grid">
						<div class="view view-tenth">
							<div class="agile_text_box">
								<i class="men"></i>
								<h3>Mesa De Ayuda</h3>
								<p>Gestionamos el siniestro con ayuda de profesionales que están capacitados para darte una rápida atención, gestionando el proceso de principio a fin.</p>
							</div>
							
						</div>
					</div>
					<div class="clearfix"> </div>
				</div>
			</div>
			<div class="clearfix"> </div>
		</div>
	</div>
{% endblock contenido %}

apps/clients/templates/app/poliza.html
{% extends 'base/base.html' %}{% load static %}

{% block contenido %}

	<div class="services">
    	<div class="container">
			{% if user.is_authenticated %}
        	<h3 class="title_denuncia">Paso N°1</h3>
        	<p class="quia">Para dar inicio al ingreso del siniestro debes validar la póliza.</p>
			{% else %}
			<h3 class="title_denuncia">Seguimiento</h3>
        	<p class="quia">Consulta el seguimiento de tu siniestro usando tu rut</p>
			{% endif %}

			<div class="auto">
				<poliza-validor 
				endpoint="{% url 'valid_policy' %}"
				nexturl="{% url 'accidents:add_accident' 0 %}"
				button_text="{{ user.is_authenticated|yesno:"Reportar Siniestro,Consultar Siniestro" }}"
				anonymous_mode="{{ user.is_authenticated|yesno:"false,true" }}"
				>
			</poliza-validor>
			</div>
			</div>
		</div>
	</div>
{% endblock contenido %}
{% block javas %}
<script>
</script>
<script src="{% static 'vue/components/main.js' %}"></script>
{% endblock javas %}

apps/clients/templates/app/siniestro.html
{% extends 'base/base.html'%} {% load static %}

{% block contenido %}
<div class="services-breadcrumb">
		<div class="container">            
		<ul>
			<li><a href="{% url 'index' %}">Inicio</a><i>|</i></li>
			<li>Ingreso de Datos Siniestro</li>
		</ul>
	</div>
</div>

<br>
<br>
<br>
<br>
<h3 class="title_denuncia">Paso N°2</h3>
<br>

    <p class="quia">Debes completar el formulario con todos los datos del siniestro.</p>
	
	{% load crispy_forms_tags %}
	<div class="contacto_siniestro">
    <div class="formulario">      
      <h1 class="ache1">Formulario de Cliente</h1>
        <h3 class="ache2">Ingresa todos los datos del cliente para luego continuar con el proceso.</h3>
          <form action="" method="POST">
		      {% csrf_token %}   
				  {{ form | crispy     
          <button type="submit" class="button_siniestro" name="enviar_formulario" id="enviar"><p>Guardar Datos</p></button>

                <p class="aviso">
                  <span class="obligatorio"> * </span>los campos son obligatorios.
                </p>          
				{{mensaje}}
          </form>
    </div>  
  </div>



{% endblock contenido %}

apps/clients/templates/app/vehiculo.html
{% extends 'base/base.html'%} {% load static %}

{% block contenido %}
<div class="services-breadcrumb">
		<div class="container">
			<ul>
				<li><a href="{% url 'index' %}">Inicio</a><i>|</i></li>
				<li>Ingreso de Datos Vehículo</li>
			</ul>
		</div>
	</div>

	<br>
<br>
<br>
<br>
<h3 class="title_denuncia">Paso N°3</h3>
<br>

    <p class="quia">Debes completar el formulario con todos los datos del siniestro.</p>
	
	{% load crispy_forms_tags %}
	<div class="contacto_siniestro">
    <div class="formulario">      
      <h1 class="ache1">Formulario de Vehículo</h1>
        <h3 class="ache2">Ingresa todos los datos del Vehículo para finalizar con el proceso.</h3>
          <form action="" method="POST">
		  {% csrf_token %}   
		  {{ form | crispy }}  
               
              
                <button type="submit" class="button_siniestro" name="enviar_formulario" id="enviar"><p>Guardar Datos</p></button>

                <p class="aviso">
                  <span class="obligatorio"> * </span>los campos son obligatorios.
                </p>          
				{{mensaje}}
          </form>
    </div>  
  </div>

{% endblock contenido %}