AutoCarChile/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('apps.core.urls')),
    path('client/', include('apps.clients.urls')),
    path('users/', include('apps.user.urls')),
    path('accidents/', include('apps.accidents.urls')),
    path('reparacion/', include('apps.reparacion.urls')),
    path('', include('apps.sucursal.urls')),

    #path('accounts/', include('django.contrib.auth.urls')),
]

apps/accidents/urls.py
from .views import (AssignCraneAccident, AssignWorkShopAccident, ListAccidentView, ListPendingAccidentView, NewAccident,DetailAccident,AssignAccident,ListAllAccidentView,AssignWorkshopCraneAccident, ReportesAccidentView)
from django.urls import path

app_name = 'accidents'

urlpatterns = [
    path('new-accident/<int:pk>',NewAccident.as_view(),name='add_accident'),
    path('accident/<int:pk>',DetailAccident.as_view(),name='view_accident'),
    path('accident/list_pending', ListPendingAccidentView.as_view(), name="pending_list"),
    path('accident/list', ListAccidentView.as_view(), name="list_accidents"),
    path('accident/list/report', ReportesAccidentView.as_view(), name="report_accidents"),
    path('accident/assing/<int:pk>', AssignAccident.as_view(), name="assing"),
    path('accident/assing/workshop/<int:pk>', AssignWorkshopCraneAccident.as_view(), name="assing_workshop"),
    # path('accident/assing/crane/<int:pk>', AssignCraneAccident.as_view(), name="assing_crane"),
    path('accident/list/all', ListAllAccidentView.as_view(), name="list"),
]

apps/core/urls.py
from django.urls import path, include
from .views import IndexView, ContactView, ListContactMessagesView, ChangeContactView
urlpatterns = [
    path('', IndexView.as_view(), name="index"),
    path('contact', ContactView.as_view(), name="contact"),
    path('contact/list/messages', ListContactMessagesView.as_view(), name="messagesContact"),
    path('change/<int:pk>/',ChangeContactView.as_view(),name = 'changeContact'),
    
]

apps/core/models.py
from django.db import models

class ContactoModel(models.Model):
    nombre = models.CharField(max_length=50,null=True)
    apellido = models.CharField(max_length=50,null=True)
    telefono = models.CharField(max_length=50,null=True)
    correo = models.EmailField(null=False)
    mensaje = models.TextField(null=False)
    leido = models.BooleanField(default=False)
    fecha = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.nombre

    class Meta:
        db_table = 'contacto'
        default_permissions = ()
        permissions = (
            ("view_contactosMensajes",     "Ver Mensajes de contactanos"),
            ("add_contactosMensajes",      "Registrar Mensajes de contactanos"),
            ("change_contactosMensajes",   "Actualizar Mensajes de contactanos"),
            ("delete_contactosMensajes",   "Eliminar Mensajes de contactanos"),
        )

    

apps/core/forms.py
from django import forms
from .models import ContactoModel
class IncializarFormulario(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for form in self.visible_fields():
            form.field.widget.attrs['class'] = 'form-control select2' if form.field.widget.__class__.__name__ == 'Select' else 'form-control'
            form.field.widget.attrs['autocomplete'] = 'off'

class ContactoForm(IncializarFormulario):
    class Meta:
        model =  ContactoModel
        fields = '__all__'
        exclude = ('leido',)
        widgets = { 
            'nombre': forms.TextInput(attrs={'placeholder': 'Nombre'}),
            'apellido' : forms.TextInput(attrs={'placeholder': 'Apellido (s)'}),
            'telefono' : forms.TextInput(attrs={'placeholder': 'Número telefonico'}),
            'correo' : forms.EmailInput(attrs={'placeholder': 'Correo electronico'}),
            'mensaje' : forms.Textarea(attrs={'placeholder': '¿Cuales son tus dudas? '}),
        }

apps/core/views.py
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import TemplateView, FormView, ListView, UpdateView
from .models import ContactoModel
from .forms import ContactoForm
from django.contrib import messages
from django.http import JsonResponse
from apps.core.mixins import StaffPermiso, PermisosRequeridos, GuardarModelo


from apps.accidents.models import Accident
from apps.reparacion.models import ReparacionModel, TipoReparacionModel
from django.contrib.sites.shortcuts import get_current_site

class IndexView(TemplateView):
    template_name = "index.html"
    #template_name = 'correos/presupuesto.html'
    def get_template_names(self):
        if self.request.user.is_authenticated:
            self.template_name = 'indexDash.html'
        return self.template_name

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['tituloPagina'] = 'Inicio'
        context['tituloSeccion'] = context['tituloPagina']

        #Prueba de template de correo
        # accidente = Accident.objects.filter(pk=5).first()
        # context["accidente"] = accidente
        # context['cotizacion'] = ReparacionModel.objects.filter(siniestro=accidente).first()
        # context['dominio'] =  get_current_site(self.request).domain if self.request else '127.0.0.1:8000'
        return context

class ContactView(GuardarModelo, FormView):
    form_class = ContactoForm
    model = ContactoModel
    template_name = 'core/contact.html'
    success_url = reverse_lazy('index')
    mensajeExito = "Datos de contacto enviados exitosamente"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['tituloPagina'] = 'Contactanos'
        context['tituloSeccion'] = 'Contacto'
        context['action'] = 'add'
        context['imagenPage'] = True
        return context

class ListContactMessagesView(PermisosRequeridos,ListView):
    model = ContactoModel
    template_name='core/contactList.html'
    permission_required = ['core.view_contactosMensajes']

    def get_queryset(self):
        return self.model.objects.all().order_by('leido')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['tituloPagina'] = 'Listado de mensajes'
        context['tituloSeccion'] = context['tituloPagina']
        context['titulo'] = 'Mensajes'
        return context


class ChangeContactView(PermisosRequeridos,UpdateView):
    model = ContactoModel
    permission_required = ['core.contactosMensajes','core.contactosMensajes']
    def post(self, request, *args, **kwargs):
        data = {}
        try:
            action = request.POST['action']
            if action == 'leer':
                self.object.leido = True
                self.object.save()
                messages.success(request, "Mensaje leido exitosamente.")
            elif action == 'nuevo':
                self.object.leido = False
                self.object.save()
                messages.success(request, "Mensaje marcado como no leido.")
            elif action == 'borrar':
                self.object.delete()
                messages.success(request, "Mensaje eliminado exitosamente.")
            else:
                return JsonResponse({'error': 'Sin opción disponible'})
        except Exception as e:
            data = {'error' : str(e)}
        return JsonResponse(data)

apps/core/templates/base/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>{{tituloPagina}}</title>

  {% include 'base/baseDash/complementos.html' %} {% block complementos %} {% endblock complementos %}


  <link rel="stylesheet" href="{% static 'adminlte/css/fontGoogle.css' %}">
  <!-- Font Awesome -->
  <link rel="stylesheet" href="{% static 'adminlte/css/all.min.css' %}">
  <!-- Theme style -->
  <link rel="stylesheet" href="{% static 'adminlte/css/adminlte.min.css' %}">

  <style>
html,
body {
    font-size: 100%;
    font-family: 'Open Sans', sans-serif;
    background: #ffffff;
}

.navbar-brand {
    padding: 0;
    line-height: 46px;
    font-size: 1.2em;
    height: 45px;
    text-transform: uppercase;
    font-weight: 600;
}
.navbar-brand span {
    transform: rotate(-180deg);
    -webkit-transform: rotate(-180deg);
    -moz-transform: rotate(-180deg);
    -o-transform: rotate(-180deg);
    -ms-transform: rotate(-180deg);
    display: inline-block;
    color: #ff9900;
    line-height: 1;
}
.logo_nav {
    padding: 1.5em 0;
}


.services-breadcrumb {
    padding: 1em 0;
    background: #f5f5f5;
    text-align: center;
}

.services-breadcrumb ul li {
    display: inline-block;
    color: #212121;
    text-transform: uppercase;
}

.services-breadcrumb ul li a {
    color: #ff9900;
    text-decoration: none;
}

.services-breadcrumb ul li a:hover {
    color: #212121;
}

.services-breadcrumb ul li i {
    padding: 0 1.5em;
}


/*-- //banner1 --*/


/*-- services --*/

.w3l_services_grid1 {
    text-align: center;
}

.w3l_services_grid1 span {
    color: #ff9900;
    font-size: 1.5em;
}

.w3l_services_grid1 h4 a {
    text-transform: capitalize;
    font-size: 1.1em;
    color: #212121;
    text-decoration: none;
    display: block;
    margin: 1em 0;
}

.w3l_services_grid1 h4 a:hover,
.w3l_services_grid:hover .w3l_services_grid1 h4 a {
    color: #ff9900;
}

.w3l_services_grid1 li {
    color: #000000;
    line-height: 2em;
    text-align: justify;
    padding: -1px;
}

.w3l_services_grid1 p {
    color: #999;
    line-height: 2em;
    text-align: justify;
}

.w3l_services_grids:nth-child(3) {
    margin: 4em 0 3em;
}

.w3l_services_grid1 span {
    overflow: hidden;
    position: relative;
}

.w3l_services_grid:hover .w3l_services_grid1 span {
    -webkit-transform: scale(1.3) translateY(1px);
    transform: scale(1.3) translateY(1px);
    -o-transform: scale(1.3) translateY(1px);
    -ms-transform: scale(1.3) translateY(1px);
    color: #212121;
}

  </style>

  <link rel="stylesheet" href="{% static 'app/css/style.css' %}">

</head>
<body class="hold-transition sidebar-mini">
<div class="wrapper">

  {% include 'base/baseDash/menuArriba.html' %}
 {% include 'base/baseDash/menuLateral.html' %}


  <div class="content-wrapper">
    <section class="content-header">
      <div class="container-fluid">
        <div class="row mb-2">
          <div class="col-sm-12">
            <ol class="breadcrumb float-sm-right">
              <li class="breadcrumb-item"><a href="{% url 'index' %}">Inicio</a></li>
              <li class="breadcrumb-item active">{{tituloSeccion}}</li>
            </ol>
          </div>
        </div>
      </div>
    </section>

    <section class="content">

      <div class="card">
        {% comment %} <div class="card-header">
          <h3 class="card-title">Title</h3>
        </div> {% endcomment %}
        <div class="card-body" id="vue-app">
          {% block contenido %}{% endblock contenido %}
        </div>
      </div>
    </section>
  </div>

  <footer class="main-footer">
    <div class="float-right d-none d-sm-block">
      <p>&copy 2021 autoCar Chile | Diseñado por SQUAD LABS</p>
    </div>
    <strong>l.ignaciomatus@gmail.com<a href="l.ignaciomatus@gmail.com"></a></strong>
  </footer>

  <!-- Control Sidebar -->
  <aside class="control-sidebar control-sidebar-dark">
    <!-- Control sidebar content goes here -->
  </aside>
  <!-- /.control-sidebar -->
</div>
<!-- ./wrapper -->
<!-- jQuery -->
<script src="{% static 'adminlte/js/jquery.min.js' %}"></script>
<!-- Bootstrap 4 -->
<script src="{% static 'adminlte/js/bootstrap.bundle.min.js' %}"></script>
<!-- AdminLTE App -->
<script src="{% static 'adminlte/js/adminlte.js' %}"></script>
<!-- AdminLTE for demo purposes -->
<script src="{% static 'adminlte/js/demo.js' %}"></script>


 <script>
        const miurl = "{{url}}";
    </script>
    <script src="{% static 'admin/static/admin/js/vendor/jquery/jquery.datetimepicker.full.js' %}"></script>
    <script src="{% static 'vue/axios.min.js' %}"></script>
    <script src="{% static 'vue/vue.js' %}"></script>
    <script src="{% static 'lib/jquery-confirm/jquery-confirm.min.js' %}"></script>
    <script src="{% static 'adminlte/js/select2.min.js' %}"></script>

    <script src="{% static 'app/core/coreFuncion.js' %}"></script>
    {% block enviarJS %}
    <script>
    $('form').on('submit', function(e) {
        e.preventDefault();
        var parametros = new FormData(this);
        formAJAX(window.location.pathname, 'Notificación', '¿Estas seguro de realizar la siguiente acción?', parametros, function(data) {
            location.href = miurl;
        });
    });
    </script>
    {% endblock enviarJS %}
    {% block javas %}{% endblock javas %} {% for message in messages %}
    <script>
        toastr.options = {
            "closeButton": true,
            "debug": false,
            "newestOnTop": true,
            "progressBar": true,
            "positionClass": "toast-top-right",
            "preventDuplicates": false,
            "onclick": null,
            "showDuration": "4000",
            "hideDuration": "4000",
            "timeOut": "4000",
            "extendedTimeOut": "4000",
            "showEasing": "swing",
            "hideEasing": "linear",
            "showMethod": "fadeIn",
            "hideMethod": "fadeOut"
        }
        toastr["{{ message.tags }}"]("{{message}}")
    </script>
    {% endfor %}


</body>
</html>

apps/core/templates/base/baseForm.html
{% extends 'base/base.html' %} {% load crispy_forms_tags %} {% load static %} {% block complementos %} {% endblock complementos %} {% block contenido %}
<div class="container">
    <div class="row centered-form">
        <div class="col-xs-12 col-sm-12 col-md-12 col-sm-offset-0 col-md-offset-0">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h3 class="panel-title">{{tituloForm}}</h3>
                </div>
                <div class="panel-body">
                    <form enctype="multipart/form-data" method="POST" id="formulario">
                        <input type="hidden" name="action" id="action" value="{{ action }}"> {% csrf_token %} {{ form.media }}

                        <div class="container-fluid">
                            <div class="form-row">
                                {% block formulario %}
                                {% for field in form %}
                                {% if columnaForm %}
                                <div class="col-xs-6 col-sm-6 col-md-6">
                                {% else %}
                                <div class="col-xs-12 col-sm-12 col-md-12">
                                {% endif %}
                                        {% if not field.is_hidden %}
                                        <label for="{{ field.id_for_label }}">{{ field.label }}</label><br>
                                        
                                        <div class="form-group">
                                            {{ field }}
                                            <small class="text-muted">{{field.help_text}}</small> {% for error in field.errors %}
                                            <span class="badge badge-danger" id="error_{{ field.name }}" name="error_{{ field.name }}">{{ error|escape }}</span> {% endfor %}
                                        </div>
                                        {% else %}
                                            {{ field }}
                                        {% endif %}
                                    </div>
                                    {% endfor %}
                                   
                                </div>
                                {% endblock formulario %}
                                 <button type="submit" class="btn btn-info btn-block">{{botonEnviar}} </button>
                    </form>
                    </div>
                    </div>
                </div>
            </div>
        </div>

        {% endblock contenido %} {% block javas %}

        {% block javasFormulario %}
        {% endblock javasFormulario %}

        {% endblock javas %}

apps/core/templates/base/baseOut.html
{% load static %}
<!DOCTYPE html>
<html>

<head>
    <title>{{tituloPagina}}</title>
    {% include 'base/complementos.html' %} {% block complementos %} {% endblock complementos %}
</head>

<body>
    {% block headerContenido %}
    <!-- header -->
    <header>
        <div class="header">
            {% include 'base/menuArriba.html' %}
        </div>
        <div class="logo_nav">
            <div class="container">
                {% include 'base/navBar.html' %}
            </div>
        </div>
    </header>
    {% endblock headerContenido %}

    {% block contenidoGeneral %}
    <main role="main" class="container">
        <div class="card-body" id="vue-app">
            <div class="content-wrapper">
                <section class="content-header">
                    {% block cabecera %}{% endblock cabecera %}
                </section>
                <div class="content">
                    <div class="container">
                        
                       
                        {% if imagenPage %}
                        <div class="banner1">
                            <div class="container">
                            </div>
                        </div>
                        {% endif %}
                         {% if tituloSeccion %}
                        <div class="services-breadcrumb">
                            <div class="container">
                                <ul>
                                    <li><a href="{% url 'index' %}">Inicio</a><i>|</i></li>
                                    <li>{{tituloSeccion}}</li>
                                </ul>
                            </div>
                        </div>
                        {% endif %}


                        {% block contenido %}{% endblock contenido %}
                    </div>
                </div>
            </div>
        </div>
    </main>
    {% endblock contenidoGeneral %}

    {% block footerPage %}
    <footer class="footer">
        <div class="container">
            <div class="agileinfo_copy_right_left">
                <p>&copy 2021 autoCar Chile | Diseñado por SQUAD LABS</p>
            </div>
            <div class="agileinfo_copy_right_right">
                <ul class="social">
                    <li>
                        <a class="social-linkedin" href="#">
                            <i></i>
                            <div class="tooltip"><span>Facebook</span></div>
                        </a>
                    </li>
                    <li>
                        <a class="social-instagram" href="#">
                            <i></i>
                            <div class="tooltip"><span>Instagram</span></div>
                        </a>
                    </li>
                </ul>
            </div>
        </div>
    </footer>
    {% endblock footerPage %}

    <script>
        const miurl = "{{url}}";
    </script>
    <script src="{% static 'admin/static/admin/js/vendor/jquery/jquery.datetimepicker.full.js' %}"></script>
    <script src="{% static 'vue/axios.min.js' %}"></script>
    <script src="{% static 'vue/vue.js' %}"></script>
    <script src="{% static 'app/core/coreFuncion.js' %}"></script>
    {% block enviarJS %}
    <script>
    $('form').on('submit', function(e) {
        e.preventDefault();
        var parametros = new FormData(this);
        formAJAX(window.location.pathname, 'Notificación', '¿Estas seguro de realizar la siguiente acción?', parametros, function(data) {
            location.href = miurl;
        });
    });
    </script>
    {% endblock enviarJS %}
    {% block javas %}{% endblock javas %} {% for message in messages %}
    <script>
        toastr.options = {
            "closeButton": true,
            "debug": false,
            "newestOnTop": true,
            "progressBar": true,
            "positionClass": "toast-top-right",
            "preventDuplicates": false,
            "onclick": null,
            "showDuration": "4000",
            "hideDuration": "4000",
            "timeOut": "4000",
            "extendedTimeOut": "4000",
            "showEasing": "swing",
            "hideEasing": "linear",
            "showMethod": "fadeIn",
            "hideMethod": "fadeOut"
        }
        toastr["{{ message.tags }}"]("{{message}}")
    </script>
    {% endfor %}

</body>

</html>

apps/core/templates/base/complementos.html
{% load static %}
<!-- for-mobile-apps -->
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="keywords" content="Truckage Responsive web template, Bootstrap Web Templates, Flat Web Templates, Android Compatible web template, 
Smartphone Compatible web template, free webdesigns for Nokia, Samsung, LG, SonyEricsson, Motorola web design" />
<script type="application/x-javascript">
    addEventListener("load", function() {
        setTimeout(hideURLbar, 0);
    }, false);

    function hideURLbar() {
        window.scrollTo(0, 1);
    }
</script>

<!-- //for-mobile-apps -->
<link href="{% static 'app/css/bootstrap.css' %}" rel="stylesheet" type="text/css" media="all" />
<link href="{% static 'app/css/style.css' %}" rel="stylesheet" type="text/css" media="all" />
<link rel="stylesheet" href="{% static 'lib/fontawesome-free/css/all.min.css' %}">

<!-- js -->
<script type="text/javascript" src="{% static 'app/js/jquery-2.1.4.min.js' %}"></script>
<!-- //js -->
<!-- load-more -->
<script>
    $(document).ready(function() {
        size_li = $("#myList li").size();
        x = 1;
        $('#myList li:lt(' + x + ')').show();
        $('#loadMore').click(function() {
            x = (x + 1 <= size_li) ? x + 1 : size_li;
            $('#myList li:lt(' + x + ')').show();
        });
        $('#showLess').click(function() {
            x = (x - 1 < 0) ? 1 : x - 1;
            $('#myList li').not(':lt(' + x + ')').hide();
        });
    });
</script>
<!-- //load-more -->
<link href='//fonts.googleapis.com/css?family=Lato:400,100,100italic,300,300italic,400italic,700,700italic,900,900italic' rel='stylesheet' type='text/css'>
<link href='//fonts.googleapis.com/css?family=Open+Sans:400,300,300italic,400italic,600,600italic,700,700italic,800,800italic' rel='stylesheet' type='text/css'>
<!-- icono -->
<link rel="icon" href="{% static 'app/images/minibanner.jpg' %}" type="image/png" />
<link rel="shortcut icon" href="{% static 'app/images/minibanner.jpg' %}" type="image/png" />

<link href="{% static 'lib/jquery-confirm/jquery-confirm.min.css' %}" rel="stylesheet">
<link rel="stylesheet" href="{% static 'lib/select2-4.0.13/css/select2.min.css' %}">
<link rel="stylesheet" href="{% static 'lib/select2-4.0.13/css/select2-bootstrap4.min.css' %}">
<link rel="stylesheet" href="{% static 'lib/toastr/toastr.min.css' %}">
<link rel="stylesheet" href="{% static 'admin/static/admin/js/vendor/jquery/jquery.datetimepicker.min.css' %}">
<link href="{% static 'lib/sweetalert2/sweetalert2.min.css' %}" rel="stylesheet">
<script src="{% static 'lib/sweetalert2/sweetalert2.min.js' %}"></script>
<script src="{% static 'lib/jquery-confirm/jquery-confirm.min.js' %}"></script>

<script src="{% static 'lib/select2-4.0.13/js/select2.min.js' %}"></script>
<script src="{% static 'lib/select2-4.0.13/js/i18n/es.js' %}"></script>
<script src="{% static 'lib/toastr/toastr.min.js' %}"></script>

 <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
<style>

</style>

apps/core/templates/base/detallesCard.html
{% extends 'base/base.html'%}{% load static %}

{% block complementos %}
<link href="{% static 'core/detallesCard.css' %}" rel="stylesheet" type="text/css" media="all" />

{% endblock %}

{% block contenido %}
<div class="page-content page-container" id="page-content">
    <div class="padding">
        <div class="row container d-flex justify-content-center">
            <div class="col-xl-6 col-md-12">
                <div class="card user-card-full">
                    <div class="row m-l-0 m-r-0">
                        <div class="col-sm-4 bg-c-lite-green user-profile">
                            <div class="card-block text-center text-white">
                            {% block izquierda %}

                            {% endblock izquierda%}
                            </div>
                        </div>
                        <div class="col-sm-8">
                            <div class="card-block">
                            {% block detallesCard %}
                            {% endblock detallesCard %}
                                
                                

                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock contenido %}

apps/core/templates/base/navBar.html
<nav class="navbar navbar-default">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        </button>
        <div class="logo">
            <h1><a class="navbar-brand" href="{% url 'index' %}">auto<span>C</span>ar Chile</span></a></h1>
        </div>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse nav-wil" id="bs-example-navbar-collapse-1">
        <nav class="link-effect-2" id="link-effect-2">
            <ul class="nav navbar-nav">
                {% if not user.is_authenticated %}
                <li class="active"><a href="{% url 'index' %}"><span data-hover="Inicio">Inicio</span></a></li>
                <li><a href="{% url 'denuncia' %}"><span data-hover="Información">Información</span></a></li>
                <li><a href="{% url 'contact' %}"><span data-hover="Contacto">Contacto</span></a></li>
                {% else %}

                {% if perms.accidents.add_accidente %}
                <li><a href="{% url 'poliza' %}"><span data-hover="Ingresar Siniestro">Ingresar Siniestro</span></a></li>
                {% endif %} {% if perms.core.view_contactomodel %}
                <li><a href="{% url 'messagesContact' %}"><span data-hover="Mis mensajes">Mensajes de contacto</span></a></li>{% endif %} {% if perms.accidents.add_accidente %} {% endif %} {% if perms.auth.view_user %}
                <li><a href="{% url 'listUser' %}"><span data-hover="Usuarios">Usuarios</span></a></li>
                {% endif %} {% if perms.auth.view_group %}
                <li><a href="{% url 'listProfile' %}"><span data-hover="Grupos">Grupos</span></a></li>
                {% endif %} {% if perms.sucursal.view_comuna %}
                <li><a href="{% url 'listComuna' %}"><span data-hover="Comuna">Comuna</span></a></li>
                {% endif %} {% if perms.sucursal.view_grua %}
                <li><a href="{% url 'listGrua' %}"><span data-hover="Grua">Grua</span></a></li>
                {% endif %} {% if perms.sucursal.view_sucursal %}
                <li><a href="{% url 'listSucursal' %}"><span data-hover="Sucursal">Sucursal</span></a></li>
                {% endif %} {% if perms.sucursal.view_taller %}
                <li><a href="{% url 'listTaller' %}"><span data-hover="Mis talleres">Mis talleres</span></a></li>
                {% endif %} {% if perms.sucursal.accept_taller %}
                <li><a href="{% url 'listTallerCar' %}"><span data-hover="Autos asignados a taller">Autos asignados a taller</span></a></li>
                {% endif %} {% if perms.reparacion.view_reparacion %}
                <li><a href="{% url 'listReparacion' %}"><span data-hover="Presupuestos pendientes">Presupuestos pendientes</span></a></li>
                {% endif %} {% if user.is_superuser %}
                <li><a href="{% url 'accidents:list' %}"><span data-hover="Siniestros Pendientes">Siniestros</span></a></li>
                {% endif %} {% if perms.accidents.asign_accidente and not user.is_superuser %}
                <li><a href="{% url 'accidents:pending_list' %}"><span data-hover="Siniestros Pendientes">Siniestros Pendientes</span></a></li>
                {% endif %} {% if perms.accidents.view_accidente and not user.is_superuser %}
                <li><a href="{% url 'accidents:list_accidents' %}"><span data-hover="Gestionar Siniestros">Gestionar Siniestros</span></a></li>
                {% endif %}

                {% endif %}
            </ul>
        </nav>
    </div>
    <!-- /.navbar-collapse -->
</nav>