AutoCarChile/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('apps.core.urls')),
    path('client/', include('apps.clients.urls')),
    path('users/', include('apps.user.urls')),
    path('accidents/', include('apps.accidents.urls')),
    path('reparacion/', include('apps.reparacion.urls')),
    path('', include('apps.sucursal.urls')),

    #path('accounts/', include('django.contrib.auth.urls')),
]

apps/accidents/urls.py
from .views import (AssignCraneAccident, AssignWorkShopAccident, ListAccidentView, ListPendingAccidentView, NewAccident,DetailAccident,AssignAccident,ListAllAccidentView,AssignWorkshopCraneAccident, ReportesAccidentView)
from django.urls import path

app_name = 'accidents'

urlpatterns = [
    path('new-accident/<int:pk>',NewAccident.as_view(),name='add_accident'),
    path('accident/<int:pk>',DetailAccident.as_view(),name='view_accident'),
    path('accident/list_pending', ListPendingAccidentView.as_view(), name="pending_list"),
    path('accident/list', ListAccidentView.as_view(), name="list_accidents"),
    path('accident/list/report', ReportesAccidentView.as_view(), name="report_accidents"),
    path('accident/assing/<int:pk>', AssignAccident.as_view(), name="assing"),
    path('accident/assing/workshop/<int:pk>', AssignWorkshopCraneAccident.as_view(), name="assing_workshop"),
    # path('accident/assing/crane/<int:pk>', AssignCraneAccident.as_view(), name="assing_crane"),
    path('accident/list/all', ListAllAccidentView.as_view(), name="list"),
]

apps/accidents/models.py
from apps.sucursal.models import TallerModel, ComunaModel, GruaModel
from django.db.models.constraints import UniqueConstraint
from django.db.models.fields.related import ForeignKey
from django.db.models.fields import DateField
from django.contrib.auth.models import User
from shortuuidfield import ShortUUIDField
from apps.clients.models import Poliza
from django.forms import model_to_dict
from django.db.models import Q
from datetime import datetime
from django.db import models


# scopes

class PendingAccidentsScope(models.Manager):
    def get_queryset(self):
        return super().get_queryset().filter(Q(grua=None) | Q(liquidador=None) | Q(taller=None))

# Create your models here.

accident_statuses = [
    [0, "Nuevo"],
    [1, "Asignada"],
    [2, "Grua en camino"],
    [3, "En taller"],
    [4, "Cotizado"],
    [5, "Reparando"],
    [6, "Terminado"],
]

class Accident(models.Model):
    fecha = models.DateTimeField(default=datetime.now)
    # poliza_nroDoc = ShortUUIDField(editable=False, unique=True)
    detalles = models.TextField(null=False,default=None)
    poliza = models.ForeignKey(Poliza,related_name="poliza_involucrada",on_delete=models.CASCADE)
    estado = models.IntegerField(choices=accident_statuses,default=0)
    grua = models.ForeignKey(GruaModel, on_delete=models.CASCADE, blank=True, null=True)
    taller = models.ForeignKey(TallerModel, on_delete=models.PROTECT, blank=True, null=True)
    comuna = models.ForeignKey(ComunaModel, on_delete=models.PROTECT , blank=True, null=True)
    liquidador = models.ForeignKey(User, on_delete=models.PROTECT, blank=True, null=True)
    direccion_incidente = models.CharField(max_length=50)
    activo = models.BooleanField(default=True)
    original_grua = None
    original_taller = None
    original_liquidador = None

    # objects = models.Manager()
    # pendings_objects = PendingAccidentsScope()
    
    def __init__(self, *args, **kwargs):
        super(Accident, self).__init__(*args, **kwargs)
        self.original_grua = self.grua
        self.original_taller = self.taller
        self.original_liquidador = self.liquidador

    def __str__(self) -> str:
        return str(self.id)
    
    def to_json(self):
        data = model_to_dict(self)
        data['estado'] = accident_statuses[self.estado][1]
        return data

    class Meta:
        ordering = ['fecha']
        db_table = 'Siniestros'
        default_permissions = ()
        permissions = (
            ("view_accidente",     "Ver Accidente/Siniestro"),
            ("add_accidente",      "Agregar Accidente/Siniestro"),
            ("change_accidente",   "Modificar Accidente/Siniestro"),
            ("delete_accidente",   "Eliminar Accidente/Siniestro"),
            ("asign_accidente",   "Asignar Accidente/Siniestro"),
            ("report_accidente",   "Ver reportes Accidente/Siniestro"),
        )

    # def save(self, force_insert=False, force_update=False, using=None, update_fields=None):
    #     print(self.grua)
    #     if self.pk:
    #         accidente = Accident.objects.filter(activo=True)
            

    #     super().save()
    #     print(self.grua)

apps/clients/models.py
from django.forms import model_to_dict
from django.db import models
import uuid

from django.db.models.fields.related import ForeignKey

# Create your models here.

class Cliente(models.Model):
    rut = models.CharField(max_length=14,unique=True)
    nombre = models.CharField(max_length=50)
    apellido = models.CharField(max_length=50)
    fecha_nacimiento = models.DateField(default=None,null=False)
    nro_doc = models.CharField(max_length=14)
    email = models.EmailField()
    telefono = models.CharField(max_length=14)
    direccion = models.CharField(max_length=50)
    # deuda_total = models.DecimalField(max_digits=10,decimal_places=2,default=0)
    
    def __str__(self):
        return self.rut

    def nombreCompleto(self):
        return self.nombre + " " + self.apellido

    class Meta:
        db_table = 'Cliente'
        default_permissions = ()
        permissions = (
            ("view_cliente",     "Ver cliente"),
            ("add_cliente",      "Registrar cliente"),
            ("change_cliente",   "Actualizar cliente"),
            ("delete_cliente",   "Eliminar cliente"),
        )


    




#------------------------------------------------------------------------------------------

class Consulta_poliza(models.Model):
    rut = models.CharField(max_length=14)
    poliza = models.CharField(max_length=10)

    def __str__(self):
        return self.rut

    class Meta:
        db_table = 'consulta_poliza'
        default_permissions = ()
        permissions = (
            ("view_consultarPoliza",     "Consultar poliza con RUT"),
        )
        
#--------------------------------------------------------------------------------------------

opciones_marcas = [
    [0, "Chevrolet"],
    [1, "Hyundai"],
    [2, "Toyota"],
    [3, "Peugeot"],
    [4, "Nissan"],
    [5, "Kia"],
    [6, "Mazda"],
    [7, "Koenigsegg"],
    [8, "Mitsubishi"],
    [9, "Chrysler"],
    [10, "Ford"],
    [11, "Chevrolet"],
    [12, "Dodge"],
]

class Vehiculo(models.Model):
    patente = models.CharField(max_length=10)
    marca = models.IntegerField(choices=opciones_marcas)
    modelo = models.CharField(max_length=50)
    year = models.CharField(max_length=4,verbose_name="año",default=None,null=True)
    nuevo = models.BooleanField(null=True)
    cliente = models.ForeignKey(Cliente,related_name="dueno_auto",on_delete=models.CASCADE)
    tipo = models.CharField(max_length=50,default=None,null=True)


    def __str__(self):
        return self.patente

    class Meta:
        db_table = 'vehiculo'
        default_permissions = ()
        permissions = (
            ("view_vehiculo",     "Ver vehiculo"),
            ("add_vehiculo",      "Registrar vehiculo"),
            ("change_vehiculo",   "Actualizar vehiculo"),
            ("delete_vehiculo",   "Eliminar vehiculo"),
        )


class Poliza(models.Model):
    numero_poliza = models.IntegerField(default=None,null=False,unique=True)
    cantidad_maxima = models.DecimalField(max_digits=10,decimal_places=2,default=1000)
    detalles = models.TextField(default=None)
    cliente = models.ForeignKey(Cliente,related_name="dueno_poliza",on_delete=models.CASCADE)
    vehiculo = models.ForeignKey(Vehiculo,related_name="vehiculo_asociado",on_delete=models.CASCADE)

    def __str__(self) -> str:
        return str(self.numero_poliza)
    
    def to_json(self):
        data = model_to_dict(self,exclude=('cliente','vehiculo',))
        data["cliente"] = model_to_dict(self.cliente)
        data["vehiculo"] = model_to_dict(self.vehiculo)
        return data

    class Meta:
        db_table = 'poliza'
        default_permissions = ()
        permissions = (
            ("view_poliza",     "Ver poliza"),
            ("add_poliza",      "Registrar poliza"),
            ("change_poliza",   "Actualizar poliza"),
            ("delete_poliza",   "Eliminar poliza"),
        )

apps/accidents/views.py
from .forms import AccidentForm,AssignAccidentForm,AssignWorkShopAccidentForm,AssignCraneAccidentForm,AssignWorkCraneAccidentForm
from apps.accidents.models import Accident,accident_statuses
from django.http import HttpResponseRedirect,JsonResponse
from apps.reparacion.models import ReparacionModel
from django.http import HttpRequest,HttpResponse
from django.views.generic.detail import DetailView
from django.views.generic.edit import UpdateView
from apps.core.mixins import PermisosRequeridos
from django.urls import reverse_lazy, reverse
from django.shortcuts import render,redirect
from apps.sucursal.models import TallerModel
from django.views.generic import CreateView
from django.views.generic import ListView
from apps.clients.models import Poliza
from django.contrib import messages
from django.http import Http404
from django.db.models import Q


# Create your views here.


class NewAccident(CreateView):
    #pemission_required = ['accidents.add_accidente']
    form_class  = AccidentForm
    template_name = "new_accident.html"
    errors = ''

    def get_policy(self, **kwargs):
        try:
            queryset = Poliza.objects.filter(pk=self.kwargs['pk'])
            obj = queryset.get()
        except queryset.model.DoesNotExist:
            raise Http404("Poliza Record no found")
        return obj
    
    def form_valid(self, form):
        return super().form_valid(form)

    def form_invalid(self, form):
        # messages.error(self.request, self.error_message)
        self.errors = form.errors
        return super().form_invalid(form)
    
    def dispatch(self,*args,**kwargs):
        policy = self.get_policy(**kwargs)
        accident = Accident.objects.filter(poliza=policy).last()
        if accident:
            if not self.request.user.is_authenticated:
                return redirect('accidents:view_accident', pk=accident.pk)
            else:
                if not self.request.user.has_perms(['accidents.add_accidente']):
                    messages.error(self.request, 'No tiene permiso para ingresar a este módulo')
                    return HttpResponseRedirect(reverse_lazy('poliza'))
            if accident.estado != 6:
                messages.error(self.request, 'No es posible registrar otro siniestro hasta que el siniestro este completo')
                return redirect('accidents:view_accident', pk=accident.pk)
        else:
            if not self.request.user.is_authenticated:
                messages.error(self.request, 'No se ha encontrado un siniestro activo para la RUT asignada' )
                return HttpResponseRedirect(reverse_lazy('poliza'))
        return super().dispatch(*args,**kwargs)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        policy = self.get_policy(**kwargs)
        context['policy'] = policy
        context['form'] = AccidentForm(initial={'poliza':policy.pk})
        context['tituloPagina'] = 'Registrar nuevo siniestro'
        context['errors'] = self.errors
        return context
    
    def get_success_url(self):
        return reverse('accidents:view_accident', kwargs={'pk' : self.object.pk})

class DetailAccident(DetailView):
    model = Accident
    template_name = 'detail_accident.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['status'] = accident_statuses[context['object'].estado][1]
        context['tituloPagina'] = 'Detalles del siniestro'
        context['tituloSeccion'] = 'Detalles del siniestro'
        context['cotizacion'] = ReparacionModel.objects.filter(siniestro=context['object']).first()
        return context

class ListPendingAccidentView(PermisosRequeridos,ListView):
    model = Accident
    template_name='list_pending_accident.html'
    permission_required = ['accidents.asign_accidente']
    queryset=Accident.objects.filter(Q(grua=None) | Q(liquidador=None) | Q(taller=None))

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['tituloPagina'] = 'Lista de Siniestros sin asignar'
        context['tituloSeccion'] = context['tituloPagina']
        context['estados'] = accident_statuses
        context['titulo'] = 'Siniestros'
        context['url'] = reverse_lazy('accidents:list_accidents')
        return context

class ListAccidentView(PermisosRequeridos,ListView):
    model = Accident
    template_name='list_accident.html'
    permission_required = ['accidents.view_accidente']
    #queryset=Accident.objects.exclude(Q(liquidador=None) | Q(taller=None))

    #def get_queryset(self):
    def get_queryset(self):
        q = self.model.objects.all().order_by('estado')
        grupos = self.request.user.groups.all()
        if grupos.filter(name__icontains='Taller').exists():
            q = q.filter(taller__in=TallerModel.objects.filter(encargado=self.request.user))
        return q

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['tituloPagina'] = 'Lista de Siniestros para gestionar'
        context['tituloSeccion'] = context['tituloPagina']
        context['estados'] = accident_statuses

        context['titulo'] = 'Siniestros'
        context['url'] = reverse_lazy('accidents:list_accidents')
        return context

class ListAllAccidentView(PermisosRequeridos,ListView):
    model = Accident
    template_name='list_accident.html'
    permission_required = ['accidents.view_accidente']

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['tituloPagina'] = 'Lista de Siniestros'
        context['tituloSeccion'] = context['tituloPagina']
        context['estados'] = accident_statuses
        context['titulo'] = 'Siniestros'
        context['url'] = reverse_lazy('accidents:list')
        return context

class ReportesAccidentView(PermisosRequeridos,ListView):
    model = Accident
    template_name='report_accident.html'
    permission_required = ['accidents.report_accidente']

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['tituloPagina'] = 'Tabla de reportes'
        context['tituloSeccion'] = context['tituloPagina']
        context['estados'] = accident_statuses
        context['titulo'] = 'Tabla de reportes'
        context['url'] = reverse_lazy('accidents:list')
        return context

class AssignAccident(PermisosRequeridos,UpdateView):
    permission_required = ['accidents.change_accidente']
    form_class  = AssignAccidentForm
    template_name = "edit_accident.html"
    model = Accident
    
    def get_success_url(self):
        return reverse('accidents:list_accidents')
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["tituloPagina"] = "Asignar Siniestro"
        context["tituloSeccion"] = "Asignar Siniestro"
        context["asignacion"] = True

        context['estados'] = accident_statuses
        return context

class AssignWorkshopCraneAccident(PermisosRequeridos,UpdateView):
    permission_required = ['accidents.change_accidente']
    form_class  = AssignWorkCraneAccidentForm
    template_name = "edit_accident.html"
    model = Accident
    
    def get_success_url(self):
        return reverse('accidents:list_accidents')
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["tituloPagina"] = "Asignar Taller"
        context["tituloSeccion"] = "Asignar Taller"
        context["asignacion"] = True

        context['estados'] = accident_statuses
        return context
        
class AssignWorkShopAccident(PermisosRequeridos,UpdateView):
    permission_required = ['accidents.change_accidente']
    form_class  = AssignWorkShopAccidentForm
    template_name = "edit_accident.html"
    model = Accident
    
    def get_success_url(self):
        return reverse('accidents:list_accidents')
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["tituloPagina"] = "Asignar Taller"
        context["tituloSeccion"] = "Asignar Taller"
        context["asignacion"] = True

        context['estados'] = accident_statuses
        return context

class AssignCraneAccident(PermisosRequeridos,UpdateView):
    permission_required = ['accidents.change_accidente']
    form_class  = AssignCraneAccidentForm
    template_name = "edit_accident.html"
    model = Accident
    
    def get_success_url(self):
        return reverse('accidents:list_accidents')
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["tituloPagina"] = "Asignar Grua"
        context["tituloSeccion"] = "Asignar Grua"
        context["asignacion"] = True

        context['estados'] = accident_statuses
        return context

apps/accidents/templates/edit_accident.html
{% extends 'base/base.html' %}{% load static %} {% load utils_tags %} {% block contenido %}

<div class="services">
    <div class="container">
        {% if asignacion %}
        <h3 class="title_denuncia">Paso N°3</h3>
        <br>
        <p class="quia">Por favor, realizar la asignación correspondiente para continuar con el proceso.</p>
        {% else %}
        <h3 class="title_denuncia">Paso N°2</h3>
        <br>
        <p class="quia">Por favor describe brevemente el siniestro, para registrarlo</p>
        {% endif %}
        <br>
        <br>

        <div class="auto">
            <p><b>Codigo: </b>{{ object.pk }}</p>
            <p><b>Detalles: </b>{{ object.detalles }}</p>
            <p><b>Comuna: </b>{{ object.comuna.nombre }}</p>
            <p><b>Estado: </b>{{ estados | get_status:object.estado }}</p>
            <p><b>Direccion: </b>{{ object.direccion_incidente }}</p>
            <form method="POST" id="form-rebel">
                {% csrf_token %} {{ form }}
                <br>
                <button onclick="document.getElementById('form-rebel').submit();" class="btn btn-success">Guardar</button>
            </form>
        </div>
    </div>
</div>
</div>
{% endblock contenido %} {% block enviarJS %} {% endblock enviarJS %} {% block javas %}
<script>
    // se declara una variable para guardar el id de la comuna y usarlo para filtrar
    var city = "{{object.comuna.pk}}";
    // esta funcion se ejecuta cada vez que select cambia de valor  y actualiza la varibale javascript de la comuna
    function setCity(value) {
        city = value;
        // se limpian los select
        $('#id_taller').val(null).trigger('change');
        $('#id_liquidador').val(null).trigger('change');
        $('#id_grua').val(null).trigger('change');
    }
    // cuando se termine de cargar la pagina, la funcion que esta dentro se ejecutara
    window.onload = function() {
        // se toma el select de taller y se convierte en un select2
        $('#id_taller').select2({
            closeOnSelect: true,
            theme: 'bootstrap4',
            width: "100%",
            // se declara que este select2 cambiara las opciones mediante un ajax
            ajax: {
                // se le da la url endpoint que nos devolvera los tallers
                url: "{% url 'buscarTaller' %}",
                // esta funcion se utiliza para declarar los parametros que se enviaran a la url
                data: function(params) {
                    // query sera un diccionario, el cual se define como sera la busqueda en el url
                    var query = {
                            q: params.term,
                            city: city,
                            type: "free"
                        }
                        //   la variable params.term contiene el texto que se escribio dentro del select2
                        // definiendo q y city la en la url se utilizaran de la siguiente manera taller/buscar?q=[params.term]&city=[city]
                    return query;
                },
                // se define que se espera un json por parte del endpoint
                dataType: 'json',
                // esta function se utiliza para transformar la respuesta del endpoint 
                // {
                // 	id:[id],
                // 	nombre:[nombre]
                // }
                // select2 necesita la siguiente estructura
                // {
                // 	id:[id],
                // 	text:[nombre]
                // }
                processResults: function(data) {
                    // se declara un array vacio donde se guardara los valores ya transformados
                    let results = [];
                    data.forEach(element => {
                        // se transforma la respuesta
                        results.push({
                            id: element.id,
                            text: element.nombre
                        });
                    });
                    return {
                        //   se devuelve un array con todas las transformaciones
                        results: results
                    };
                }
            }
        });
        $('#id_liquidador').select2({
            closeOnSelect: true,
            theme: 'bootstrap4',
            width: "100%",
            ajax: {
                url: "{% url 'buscarLiquidador' %}",
                data: function(params) {
                    var query = {
                        q: params.term,
                        city: city,
                        type: "free",
                    }
                    return query;
                },
                dataType: 'json',
                processResults: function(data) {
                    let results = [];
                    data.forEach(element => {
                        results.push({
                            id: element.usuario__id,
                            text: element.usuario__first_name
                        });
                    });
                    return {
                        results: results
                    };
                }
            }
        });
        $('#id_grua').select2({
            closeOnSelect: true,
            theme: 'bootstrap4',
            width: "100%",
            ajax: {
                url: "{% url 'buscarGrua' %}",
                data: function(params) {
                    var query = {
                        q: params.term,
                        city: city,
                        type: "free",
                    }
                    return query;
                },
                dataType: 'json',
                processResults: function(data) {
                    let results = [];
                    data.forEach(element => {
                        results.push({
                            id: element.id,
                            text: element.patente
                        });
                    });
                    return {
                        results: results
                    };
                }
            }
        });
    };
</script>
{% endblock javas %}

apps/accidents/templates/list_accident.html
{% extends 'base/listado.html' %} {% load static %} {% load utils_tags %}
{% block permisoAgregar %}
{% if perms.accidents.add_accidente %}
<a class="btn btn-primary" href="{% url 'poliza' %}">
    <i class="fas fa-car-crash"></i> Ingresar siniestro
</a>
{% endif %} {% endblock %}


 {% block crearTabla %} {% if perms.accidents.view_accidente %}
 <div class="text-center">
    <h3>Lista de Siniestros para Gestionar</h3>
 </div>
<thead class="btn-primary text-dark">
    <tr>
        <td>Fecha</td>
        <td>Nro Siniestro</td>
        <td>RUT Cliente</td>
        <td>Nombre Cliente</td>
        <td>Estado</td>
        <td>Liquidador</td>
        <td>Taller</td>
        <td>Grua</td>
        <td>Acciones</td>
    </tr>
</thead>
<tbody>
    {% for p in object_list %}
    <tr>
        <td>{{ p.fecha }}</td>
        <td>{{ p.pk }}</td>
        <td>{{ p.poliza.cliente }}</td>
        <td>{{ p.poliza.cliente.nombre }} {{ p.poliza.cliente.apellido }}</td>
        <td>{{ estados | get_status:p.estado }}</td>
        <td>{% if p.liquidador %} {{ p.liquidador.get_full_name }} {% else %} NA {% endif%}</td>
        <td>{% if p.taller %} {{ p.taller }} {% else %} NA {% endif%}</td>
        <td>{% if p.grua %} {{ p.grua }} {% else %} NA {% endif%}</td>

        <td class="text-center">
            {% autoescape off %}
                {% get_accidents_links p user perms %}
            {% endautoescape %}
        </td>
    </tr>
    {% endfor %}
</tbody>
{% endif %} {% endblock crearTabla %}

{% block jsListado %}
<script src="{% static 'taller/tallerList.js' %}"></script>
{% endblock jsListado %}

apps/accidents/templates/list_pending_accident.html
{% extends 'base/listado.html' %} {% load utils_tags %} {% block crearTabla %} {% if perms.accidents.asign_accidente %}
<thead class="btn-primary text-dark">
    <tr>
        <td>Fecha</td>
        <td>Nro Siniestro</td>
        <td>Poliza</td>
        <td>Estado</td>
        <td>Comuna</td>
        <td>Detalles</td>
        <td>Acciones</td>
    </tr>
</thead>
<tbody>
    {% for p in object_list %}
    <tr>
        <td>{{p.fecha}}</td>
        <td>{{ p.pk }}</td>
        <td>{{ p.poliza }}</td>
        <td>{{ estados | get_status:p.estado }}</td>
        <td>{{ p.comuna }}</td>
        <td>{{ p.detalles }}</td>

        <td class="text-center">
            {% if perms.accidents.asign_accidente %}
            <a href="{% url 'accidents:assing' p.id %}" class="btn btn-warning btn-xs btn-flat"><i class="fas fa-user-edit"></i>  Asignar</a> {% endif %} {% if perms.accidents.delete_accidente %}
            <button type="button" data-url="{% url 'accidents:assing' p.id %}" datos="{{ p.id }}" class="btn btn-danger btn-xs btn-flat eliminar"><i class="fas fa-trash-alt"></i></button> {%endif%}
        </td>
    </tr>
    {% endfor %}
</tbody>
{% endif %} {% endblock crearTabla %}

apps/accidents/templates/new_accident.html
{% extends 'base/base.html' %}{% load static %} {% load humanize %}

{% block contenido %}
	<div class="services">
    	<div class="container">
        	<h3 class="title_denuncia">Paso N°2</h3>
        	<p class="quia">Por favor describe brevemente el siniestro, para registrarlo</p>
			<div class="auto">
				<form method="POST" id="form-rebel">
					{% csrf_token %}
					<div style="color: red;">
						{{ errors }}
					</div>
					<label>Poliza: </label>{{ policy.pk }}
					<br>
					<label>Cantidad Maxima de cobertura: </label>{{ policy.cantidad_maxima|floatformat:0|intcomma }}
					<br>
                    {{ form }}
					<br>
                    <button onclick="document.getElementById('form-rebel').submit();" class="btn btn-success">Guardar</button>
                </form>
			</div>
			</div>
		</div>
	</div>
{% endblock contenido %}

{% block enviarJS %}
{% endblock enviarJS %}
{% block javas %}
<script>
	// se declara una variable para guardar el id de la comuna y usarlo para filtrar
	var city = 0;
	// esta funcion se ejecuta cada vez que select cambia de valor  y actualiza la varibale javascript de la comuna
	function setCity(value){
		city = value;
		// se limpian los select
		$('#id_taller').val(null).trigger('change');
		$('#id_liquidador').val(null).trigger('change');
		$('#id_grua').val(null).trigger('change');
	}
	// cuando se termine de cargar la pagina, la funcion que esta dentro se ejecutara
	window.onload = function(){
		$('#id_fecha').datetimepicker({
			format: "d/m/Y H:i",
		});
		// se toma el select de taller y se convierte en un select2
		$('#id_taller').select2({
		closeOnSelect: true,
    	theme: 'bootstrap4',
    	width: "100%",
		// se declara que este select2 cambiara las opciones mediante un ajax
  		ajax: {
			// se le da la url endpoint que nos devolvera los tallers
    		url:"{% url 'buscarTaller' %}",
			// esta funcion se utiliza para declarar los parametros que se enviaran a la url
			data: function (params) {
				// query sera un diccionario, el cual se define como sera la busqueda en el url
      			var query = {
        			q: params.term,
        			city: city,
					type: "free"
      			}
				//   la variable params.term contiene el texto que se escribio dentro del select2
				// definiendo q y city la en la url se utilizaran de la siguiente manera taller/buscar?q=[params.term]&city=[city]
      			return query;
    		},
			// se define que se espera un json por parte del endpoint
    		dataType: 'json',
			// esta function se utiliza para transformar la respuesta del endpoint 
			// {
			// 	id:[id],
			// 	nombre:[nombre]
			// }
			// select2 necesita la siguiente estructura
			// {
			// 	id:[id],
			// 	text:[nombre]
			// }
			processResults: function (data) {
				// se declara un array vacio donde se guardara los valores ya transformados
				let results = [];
				data.forEach(element => {
					// se transforma la respuesta
					results.push({id:element.id,text:element.nombre});
				});
      			return {
					//   se devuelve un array con todas las transformaciones
        			results: results
      			};
    		}
  		}
		});
		$('#id_liquidador').select2({
			closeOnSelect: true,
    		theme: 'bootstrap4',
    		width: "100%",
			ajax: {
			url:"{% url 'buscarLiquidador' %}",
			data: function (params) {
	  			var query = {
        			q: params.term,
        			city: city,
					type: "free",
      			}
	  			return query;
    		},
			dataType: 'json',
			processResults: function (data) {
				let results = [];
				data.forEach(element => {
					results.push({id:element.usuario__id,text:element.usuario__first_name});
				});
      			return {
	    			results: results
      			};
    		}
  			}
		});
		$('#id_grua').select2({
		closeOnSelect: true,
    	theme: 'bootstrap4',
    	width: "100%",
		ajax: {
			url:"{% url 'buscarGrua' %}",
			data: function (params) {
	  			var query = {
        			q: params.term,
        			city: city,
					type: "free",
      			}
	  			return query;
    		},
			dataType: 'json',
			processResults: function (data) {
				let results = [];
				data.forEach(element => {
					results.push({id:element.id,text:element.patente});
				});
      			return {
	    			results: results
      			};
    		}
  			}
		});
	};
</script>
{% endblock javas %} 